// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5FtFmLH5ytYzjfeuMqcpi7Uvxufz6ENM',
    appId: '1:150862305798:web:12b6619a911c948b500187',
    messagingSenderId: '150862305798',
    projectId: 'fluentfocus-27aad',
    authDomain: 'fluentfocus-27aad.firebaseapp.com',
    storageBucket: 'fluentfocus-27aad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjdAGY1Lf4JeEp25aLRe3CmzFAzUj2TTk',
    appId: '1:150862305798:android:bbd557b870dfc8df500187',
    messagingSenderId: '150862305798',
    projectId: 'fluentfocus-27aad',
    storageBucket: 'fluentfocus-27aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkRXnopDiYhDUl8GoPxZhnIdTVTAMYWOc',
    appId: '1:150862305798:ios:aecaaa408807137b500187',
    messagingSenderId: '150862305798',
    projectId: 'fluentfocus-27aad',
    storageBucket: 'fluentfocus-27aad.appspot.com',
    iosClientId: '150862305798-66b3lac9kjtoar2mm3f9fqv0d0qfvh94.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
